rnpm/rnpm-plugin-link

- package.json
- src/action.js
- src/android/copyAssets.js
- src/ios/copyAssets.js
- src/utils.js
It now detects file type and handles fonts differently than the rest (well, for now it does nothing apart from that but can be easily patched in the future)
For Android, it just copies all the fonts to `targetPath/fonts` folder preserving the original name.
For iOS, it creates group reference to original fonts directory.
> Better `copyAssets` 

- src/ios/copyAssets.js
Because `project.getBuildProperty('INFOPLIST_FILE')` returns e.g. `"/src/Info.plist"` and we need to remove quotes. This has different behaviour when using with `npm link` apparently since I am not experiencing that locally.
> Fix one issue with info.plist path

- src/ios/copyAssets.js
It seems Cocoapods adds this to pbxProject (unconfirmed) and this line is breaking plist parsing.
> Cut $(SRCROOT) from pblistPath

- src/action.js
Our recent changes introduced possible error to be thrown when `package.json` does not exist. This pull request updates our interface to that so we still keep printing out nice, readable message after all.
> Update to latest `rnpm` interface

- package.json
- src/action.js
This is related to rnpm pr. The only thing that has changed is that we `map` dependency configs first into an array, so we can split main function into smaller bits and re-use that array.
> Add project assets if they are present

- src/android/registerNativeModule.js
Currently, it hardcodes `/android` as the path even if a dependency
specifies a sourceDir. When a dependency specifies a sourceDir, that
should be respected and added to settings.gradle
> Use a dependency's sourceDir when writing to settings.gradle

- src/ios/getHeaderSearchPath.js
Tests fail on Windows since an incorrect path separator was used. Instead of hard coding `\`, this PR basically adds `path.sep`, thus adding the right path. This way, iOS projects can be linked from Windows also.
> Fix the path seperator when searching for iOS header files

- README.md
- package.json
- src/link.js
- test/link.spec.js
As we discussed in Discord, I've made a standalone repo for hooks wrapper.
Basically, since now, users can make their own plugins with a hooks support.
Basically, I moved `makeHook` function to the standalone repo to allow other people use it.
Replace in-place function by the `rnpm-hooks` module. Added missing `require` for testing and adjusted link code to take care about generating hooks. I'd like to keep `rnpm-hooks` as tiny as possible (and not to depend on our `dependency` object structure), so I think [this kind of logic](https://github.com/rnpm/rnpm-plugin-link/compare/chore/better-hooks?expand=1#diff-1dbe17fda47e0a0d65b16ad4646552d0R103) should be scoped in this specific plugin.
See [rnpm-hooks](https://github.com/rnpm/rnpm-hooks) for the further reading.
> Introduce prelink and postlink commands

- package.json
- src/android/patches/makeSettingsPatch.js
- test/android/patches/makeSettingsPatch.spec.js
settings.gradle is not always inside sourceDir, see -> https://github.com/rnpm/rnpm/blob/master/src/config/android/index.js#L41-L45. That PR changes the patch to always use `settings.gradle` real location (since we already expose it from rnpm config)
> Fix wrong settings gradle patch

- src/android/registerNativeModule.js
Fixes https://github.com/rnpm/rnpm-plugin-link/issues/27.
The original way of checking for the presence of `new PackageClassName()` inside the MainActivity could fail in the following scenarios:
1. If the PackageClassName object requires extra parameters in construction, e.g `new PackageClassName(params...)`;
2. If the `PackageClassName` object is a private instance and not directly constructed, e.g. https://github.com/Microsoft/react-native-code-push/blob/master/Examples/CodePushDemoApp/android/app/src/main/java/com/microsoft/codepushdemoapp/MainActivity.java#L54
In general, looking into Java code to detect linkage is not foolproof because code is relatively non static and is always changed over the lifetime of a project.
This change proposes looking into the `build.gradle` file to …
> More foolproof way of checking plugin installation

- src/android/getPrefix.js
- src/android/patches/0.20/addPackagePatch.js
- src/android/patches/0.20/makeMainActivityPatch.js
1. The MainActivity.java have a small change in RN 0.20 (see https://github.com/facebook/react-native/commit/abdca047b0d3a1f9627a485c15fad0b99c5c241e).
2. Let android/getPrefix.js support multi versions.
> Add 0.20 patch for Android

- src/android/patches/makeSettingsPatch.js
Fixes https://github.com/rnpm/rnpm/issues/113
Builds on and replaces https://github.com/rnpm/rnpm-plugin-link/pull/36 that seems abandoned
> Replace Path backslashes in makeSettingsPatch on Windows

- src/ios/createGroup.js
- src/ios/getGroup.js
- src/ios/registerNativeModule.js
- src/ios/unlinkAssets.js
- src/ios/unregisterNativeModule.js
- test/fixtures/project.pbxproj
- test/ios/createGroup.spec.js
- test/ios/getGroup.spec.js
What this PR does:
- You can specify nested `libraryFolder`, see my comment below,
- When you have multiple groups with the same name, we no longer pick the wrong one, see: https://github.com/rnpm/rnpm/issues/111#issuecomment-202984773
Technical explanation:
Problem is - `pbxGroupByName` will return first matching group by name (regardless of nesting level). We loop recursively over all groups with our new function and also support paths, e.g. `NestedGroup/Libraries`, so if you would prefer to use libraries group that's not top-level, you can easily override that.
That PR also implements the above for `createGroup`.
> Handle nested groups

- src/ios/getPlistPath.js
This PR fixes getPlistPath return value, at current version it returns null or undefined
> getPlistPath return value fix

- src/android/getPrefix.js
- test/getPrefix.spec.js
Currently:
```javascript
let rnVersion = '0.24.0-rc1';
const version = rnVersion.replace('-rc', ''); // becomes '0.24.01'
...
if (semver.lt(version, item + '.0') && nextVersion) // throws exception since version is not valid semver
```
Fixed this, and also updated the unit tests.
> Fix error when RN version is x.x.x-rc1

- src/link.js
- test/link.spec.js
The `promisify` helper went too deep with the arrow functions. Added a test to ensure these commands are called in the right order.
Fixes #64
> Fix for prelink/postlink commands not being called

- src/android/patches/makeSettingsPatch.js
- test/android/patches/makeSettingsPatch.spec.js
Fixes https://github.com/rnpm/rnpm/issues/153
Since the pattern is `include ':app:'\n`, we have to preserve the `\n` when we are done with inserting.
> Preserve line breaks in settings.gradle

- src/android/patches/applyPatch.js
- src/android/patches/makeBuildPatch.js
Fixes #75 
This PR originally just added a regexp pattern (see `makeBuildPatch`). It won't pick any `dependencies {` block if it's starting with a space or a tab (handles nesting).
However, I had to modify the way we apply patches.
The original code was:
```js
replace(patch.pattern, `${patch.pattern}${patch.patch}`)
```
and that was replacing a found match with a regex & patch, e.g.:
```
/[^ \t]dependencies {\n
compile()
}
```
since we never expected a `pattern` to be regexp.
The new code passes a function, that given a match for a given pattern, can use it to return a string to replace (e.g. match + pattern). That handles regexp being used as a pattern as we are given a real match. For plain strings, it works as previously.
Regexp can be tested here http://www.regexr.com/3dbbp
> Improve build.gradle patch

- src/android/registerNativeModule.js
- src/android/unregisterNativeModule.js
- src/ios/unregisterNativeModule.js
- src/unlink.js
Scope:
1) Remove `return` value from `registerDependencyAndroid` as these functions should not have return value
2) Remove `isInstalled` checks and return values from `unregister` versions as these functions should not have return value and the check is done separately
3) Add `isInstalled` check inside `unlink`
4) Fix scope in try-catch block for ES6 compatibility 
This PR is important to ship as it looks like https://github.com/rnpm/rnpm-plugin-link/pull/70/files#diff-7c8e252a3de28dabaaf67dd7fdf34a29L64 already did point 2 for `android`. That means on Android, we do not check if dependency is installed before linking.
> Update `unlink` interface

- src/unlink.js
- test/getDependencyConfig.spec.js
- test/unlink.spec.js
The assets that should be kept were not properly specified. Also added a test for unlink that includes testing removing only the assets not used by other dependencies or the project itself.
> Fix bug where wrong assets are removed in unlink

- package.json
- src/ios/addSharedLibraries.js
- src/ios/copyAssets.js
- src/ios/createGroupWithMessage.js
- src/ios/registerNativeModule.js
- src/ios/removeSharedLibraries.js
- src/ios/unregisterNativeModule.js
- src/unlink.js
- test/ios/addSharedLibraries.spec.js
- test/ios/removeSharedLibraries.spec.js
When removing shared libraries, only the ones not used by anyone else are removed.
The xcode module was updated to 0.8.8 for supporting `tbd` files (text-based dynamic library definitions).
This resolves rnpm/rnpm#122 and only works with rnpm/rnpm#172 merged, which provided the `sharedLibraries` array.
> Support adding/removing iOS shared libraries
